<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // Mapear nomes dos distritos para IDs
        $distritosMap = [
            1 => 'Aveiro',
            2 => 'Beja',
            3 => 'Braga',
            4 => 'Bragança',
            5 => 'Castelo Branco',
            6 => 'Coimbra',
            7 => 'Évora',
            8 => 'Faro',
            9 => 'Guarda',
            10 => 'Leiria',
            11 => 'Lisboa',
            12 => 'Portalegre',
            13 => 'Porto',
            14 => 'Santarém',
            15 => 'Setúbal',
            16 => 'Viana do Castelo',
            17 => 'Vila Real',
            18 => 'Viseu',
            19 => 'Angra do Heroísmo',
            20 => 'Horta',
            21 => 'Ponta Delgada',
            22 => 'Funchal',
        ];

        // Obter IDs reais dos distritos da BD
        $distritosIds = [];
        foreach ($distritosMap as $oldId => $nome) {
            $distrito = DB::table('distritos')->where('nome', $nome)->first();
            if ($distrito) {
                $distritosIds[$oldId] = $distrito->id;
            }
        }

        $concelhos = [
            ['Águeda', 1],
            ['Albergaria-A-Velha', 1],
            ['Anadia', 1],
            ['Arouca', 1],
            ['Aveiro', 1],
            ['Castelo de Paiva', 1],
            ['Espinho', 1],
            ['Estarreja', 1],
            ['Santa Maria da Feira', 1],
            ['Ílhavo', 1],
            ['Mealhada', 1],
            ['Murtosa', 1],
            ['Oliveira de Azemeis', 1],
            ['Oliveira do Bairro', 1],
            ['Ovar', 1],
            ['S. João da Madeira', 1],
            ['Sever do Vouga', 1],
            ['Vagos', 1],
            ['Vale de Cambra', 1],
            ['Aljustrel', 2],
            ['Almodovar', 2],
            ['Alvito', 2],
            ['Barrancos', 2],
            ['Beja', 2],
            ['Castro Verde', 2],
            ['Cuba', 2],
            ['Ferreira do Alentejo', 2],
            ['Mértola', 2],
            ['Moura', 2],
            ['Odemira', 2],
            ['Ourique', 2],
            ['Serpa', 2],
            ['Vidigueira', 2],
            ['Amares', 3],
            ['Barcelos', 3],
            ['Braga', 3],
            ['Cabeceiras de Basto', 3],
            ['Celorico de Basto', 3],
            ['Esposende', 3],
            ['Fafe', 3],
            ['Guimarães', 3],
            ['Povoa de Lanhoso', 3],
            ['Terras de Bouro', 3],
            ['Vieira do Minho', 3],
            ['Vila Nova de Famalicão', 3],
            ['Vila Verde', 3],
            ['Vizela', 3],
            ['Alfândega da Fé', 4],
            ['Bragança', 4],
            ['Carrazeda de Ansiães', 4],
            ['Freixo de Espada à Cinta', 4],
            ['Macedo de Cavaleiros', 4],
            ['Miranda do Douro', 4],
            ['Mirandela', 4],
            ['Mogadouro', 4],
            ['Torre de Moncorvo', 4],
            ['Vila Flor', 4],
            ['Vimioso', 4],
            ['Vinhais', 4],
            ['Belmonte', 5],
            ['Castelo Branco', 5],
            ['Covilhã', 5],
            ['Fundão', 5],
            ['Idanha-A-Nova', 5],
            ['Oleiros', 5],
            ['Penamacor', 5],
            ['Proença-a-Nova', 5],
            ['Sertã', 5],
            ['Vila de Rei', 5],
            ['Vila Velha de Rodão', 5],
            ['Arganil', 6],
            ['Cantanhede', 6],
            ['Coimbra', 6],
            ['Condeixa-A-Nova', 6],
            ['Figueira da Foz', 6],
            ['Gois', 6],
            ['Lousã', 6],
            ['Mira', 6],
            ['Miranda do Corvo', 6],
            ['Montemor-O-Velho', 6],
            ['Oliveira do Hospital', 6],
            ['Pampilhosa da Serra', 6],
            ['Penacova', 6],
            ['Penela', 6],
            ['Soure', 6],
            ['Tabua', 6],
            ['Vila Nova de Poiares', 6],
            ['Alandroal', 7],
            ['Arraiolos', 7],
            ['Borba', 7],
            ['Estremoz', 7],
            ['Évora', 7],
            ['Montemor-O-Novo', 7],
            ['Mora', 7],
            ['Mourão', 7],
            ['Portel', 7],
            ['Redondo', 7],
            ['Reguengos de Monsaraz', 7],
            ['Vendas Novas', 7],
            ['Viana do Alentejo', 7],
            ['Vila Viçosa', 7],
            ['Albufeira', 8],
            ['Alcoutim', 8],
            ['Aljezur', 8],
            ['Castro Marim', 8],
            ['Faro', 8],
            ['Lagoa (algarve)', 8],
            ['Lagos', 8],
            ['Loulé', 8],
            ['Monchique', 8],
            ['Olhão', 8],
            ['Portimão', 8],
            ['S. Bras de Alportel', 8],
            ['Silves', 8],
            ['Tavira', 8],
            ['Vila do Bispo', 8],
            ['Vila Real de Santo Antonio', 8],
            ['Aguiar da Beira', 9],
            ['Almeida', 9],
            ['Celorico da Beira', 9],
            ['Figueira de Castelo Rodrigo', 9],
            ['Fornos de Algodres', 9],
            ['Gouveia', 9],
            ['Guarda', 9],
            ['Manteigas', 9],
            ['Mêda', 9],
            ['Pinhel', 9],
            ['Sabugal', 9],
            ['Seia', 9],
            ['Trancoso', 9],
            ['Vila Nova de Foz Côa', 9],
            ['Alcobaça', 10],
            ['Alvaiazere', 10],
            ['Ansião', 10],
            ['Batalha', 10],
            ['Bombarral', 10],
            ['Caldas da Rainha', 10],
            ['Castanheira de Pera', 10],
            ['Figueiro dos Vinhos', 10],
            ['Leiria', 10],
            ['Marinha Grande', 10],
            ['Nazare', 10],
            ['Óbidos', 10],
            ['Pedrogão Grande', 10],
            ['Peniche', 10],
            ['Pombal', 10],
            ['Porto de Mos', 10],
            ['Alenquer', 11],
            ['Arruda dos Vinhos', 11],
            ['Azambuja', 11],
            ['Cadaval', 11],
            ['Cascais', 11],
            ['Lisboa', 11],
            ['Loures', 11],
            ['Lourinhã', 11],
            ['Mafra', 11],
            ['Oeiras', 11],
            ['Sintra', 11],
            ['Sobral de Monte Agraço', 11],
            ['Torres Vedras', 11],
            ['Vila Franca de Xira', 11],
            ['Amadora', 11],
            ['Odivelas', 11],
            ['Alter do Chão', 12],
            ['Arronches', 12],
            ['Avis', 12],
            ['Campo Maior', 12],
            ['Castelo de Vide', 12],
            ['Crato', 12],
            ['Elvas', 12],
            ['Fronteira', 12],
            ['Gavião', 12],
            ['Marvão', 12],
            ['Monforte', 12],
            ['Nisa', 12],
            ['Ponte de Sor', 12],
            ['Portalegre', 12],
            ['Sousel', 12],
            ['Amarante', 13],
            ['Baião', 13],
            ['Felgueiras', 13],
            ['Gondomar', 13],
            ['Lousada', 13],
            ['Maia', 13],
            ['Marco de Canaveses', 13],
            ['Matosinhos', 13],
            ['Paços de Ferreira', 13],
            ['Paredes', 13],
            ['Penafiel', 13],
            ['Porto', 13],
            ['Póvoa de Varzim', 13],
            ['Santo Tirso', 13],
            ['Valongo', 13],
            ['Vila do Conde', 13],
            ['Vila Nova de Gaia', 13],
            ['Trofa', 13],
            ['Abrantes', 14],
            ['Alcanena', 14],
            ['Almeirim', 14],
            ['Alpiarça', 14],
            ['Benavente', 14],
            ['Cartaxo', 14],
            ['Chamusca', 14],
            ['Constancia', 14],
            ['Coruche', 14],
            ['Entroncamento', 14],
            ['Ferreira do Zezere', 14],
            ['Golegã', 14],
            ['Mação', 14],
            ['Rio Maior', 14],
            ['Salvaterra de Magos', 14],
            ['Santarem', 14],
            ['Sardoal', 14],
            ['Tomar', 14],
            ['Torres Novas', 14],
            ['Vila Nova da Barquinha', 14],
            ['Ourém', 14],
            ['Alcácer do Sal', 15],
            ['Alcochete', 15],
            ['Almada', 15],
            ['Barreiro', 15],
            ['Grandola', 15],
            ['Moita', 15],
            ['Montijo', 15],
            ['Palmela', 15],
            ['Santiago do Cacem', 15],
            ['Seixal', 15],
            ['Sesimbra', 15],
            ['Setúbal', 15],
            ['Sines', 15],
            ['Arcos de Valdevez', 16],
            ['Caminha', 16],
            ['Melgaço', 16],
            ['Monção', 16],
            ['Paredes de Coura', 16],
            ['Ponte da Barca', 16],
            ['Ponte de Lima', 16],
            ['Valença', 16],
            ['Viana do Castelo', 16],
            ['Vila Nova de Cerveira', 16],
            ['Alijó', 17],
            ['Boticas', 17],
            ['Chaves', 17],
            ['Mesão Frio', 17],
            ['Mondim de Basto', 17],
            ['Montalegre', 17],
            ['Murça', 17],
            ['Peso da Régua', 17],
            ['Ribeira de Pena', 17],
            ['Sabrosa', 17],
            ['Santa Marta de Penaguião', 17],
            ['Valpaços', 17],
            ['Vila Pouca de Aguiar', 17],
            ['Vila Real', 17],
            ['Armamar', 18],
            ['Carregal do Sal', 18],
            ['Castro Daire', 18],
            ['Cinfães', 18],
            ['Lamego', 18],
            ['Mangualde', 18],
            ['Moimenta da Beira', 18],
            ['Mortagua', 18],
            ['Nelas', 18],
            ['Oliveira de Frades', 18],
            ['Penalva do Castelo', 18],
            ['Penedono', 18],
            ['Resende', 18],
            ['Santa Comba Dão', 18],
            ['S. João da Pesqueira', 18],
            ['S. Pedro do Sul', 18],
            ['Sátão', 18],
            ['Sernancelhe', 18],
            ['Tabuaço', 18],
            ['Tarouca', 18],
            ['Tondela', 18],
            ['Vila Nova de Paiva', 18],
            ['Viseu', 18],
            ['Vouzela', 18],
            ['Angra do Heroismo', 19],
            ['Calheta (açores)', 19],
            ['Santa Cruz da Graciosa', 19],
            ['Velas', 19],
            ['Vila Praia da Vitoria', 19],
            ['Corvo', 20],
            ['Horta', 20],
            ['Lajes das Flores', 20],
            ['Lajes do Pico', 20],
            ['Madalena', 20],
            ['Santa Cruz das Flores', 20],
            ['S. Roque do Pico', 20],
            ['Lagoa (açores)', 21],
            ['Nordeste', 21],
            ['Ponta Delgada', 21],
            ['Povoação', 21],
            ['Ribeira Grande', 21],
            ['Vila Franca do Campo', 21],
            ['Vila do Porto', 21],
            ['Calheta (madeira)', 22],
            ['Câmara de Lobos', 22],
            ['Funchal', 22],
            ['Machico', 22],
            ['Ponta do Sol', 22],
            ['Porto Moniz', 22],
            ['Porto Santo', 22],
            ['Ribeira Brava', 22],
            ['Santa Cruz', 22],
            ['Santana', 22],
            ['S. Vicente', 22],
        ];

        foreach ($concelhos as [$nome, $oldDistritoId]) {
            if (isset($distritosIds[$oldDistritoId])) {
                DB::table('concelhos')->insertOrIgnore([
                    'nome' => $nome,
                    'id_distrito' => $distritosIds[$oldDistritoId],
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);
            }
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        $nomes = [
            'Águeda', 'Albergaria-A-Velha', 'Anadia', 'Arouca', 'Aveiro', 'Castelo de Paiva', 'Espinho', 'Estarreja',
            'Santa Maria da Feira', 'Ílhavo', 'Mealhada', 'Murtosa', 'Oliveira de Azemeis', 'Oliveira do Bairro', 'Ovar',
            'S. João da Madeira', 'Sever do Vouga', 'Vagos', 'Vale de Cambra', 'Aljustrel', 'Almodovar', 'Alvito', 'Barrancos',
            'Beja', 'Castro Verde', 'Cuba', 'Ferreira do Alentejo', 'Mértola', 'Moura', 'Odemira', 'Ourique', 'Serpa', 'Vidigueira',
            'Amares', 'Barcelos', 'Braga', 'Cabeceiras de Basto', 'Celorico de Basto', 'Esposende', 'Fafe', 'Guimarães',
            'Povoa de Lanhoso', 'Terras de Bouro', 'Vieira do Minho', 'Vila Nova de Famalicão', 'Vila Verde', 'Vizela',
            'Alfândega da Fé', 'Bragança', 'Carrazeda de Ansiães', 'Freixo de Espada à Cinta', 'Macedo de Cavaleiros',
            'Miranda do Douro', 'Mirandela', 'Mogadouro', 'Torre de Moncorvo', 'Vila Flor', 'Vimioso', 'Vinhais',
            'Belmonte', 'Castelo Branco', 'Covilhã', 'Fundão', 'Idanha-A-Nova', 'Oleiros', 'Penamacor', 'Proença-a-Nova',
            'Sertã', 'Vila de Rei', 'Vila Velha de Rodão', 'Arganil', 'Cantanhede', 'Coimbra', 'Condeixa-A-Nova',
            'Figueira da Foz', 'Gois', 'Lousã', 'Mira', 'Miranda do Corvo', 'Montemor-O-Velho', 'Oliveira do Hospital',
            'Pampilhosa da Serra', 'Penacova', 'Penela', 'Soure', 'Tabua', 'Vila Nova de Poiares', 'Alandroal', 'Arraiolos',
            'Borba', 'Estremoz', 'Évora', 'Montemor-O-Novo', 'Mora', 'Mourão', 'Portel', 'Redondo', 'Reguengos de Monsaraz',
            'Vendas Novas', 'Viana do Alentejo', 'Vila Viçosa', 'Albufeira', 'Alcoutim', 'Aljezur', 'Castro Marim', 'Faro',
            'Lagoa (algarve)', 'Lagos', 'Loulé', 'Monchique', 'Olhão', 'Portimão', 'S. Bras de Alportel', 'Silves', 'Tavira',
            'Vila do Bispo', 'Vila Real de Santo Antonio', 'Aguiar da Beira', 'Almeida', 'Celorico da Beira',
            'Figueira de Castelo Rodrigo', 'Fornos de Algodres', 'Gouveia', 'Guarda', 'Manteigas', 'Mêda', 'Pinhel', 'Sabugal',
            'Seia', 'Trancoso', 'Vila Nova de Foz Côa', 'Alcobaça', 'Alvaiazere', 'Ansião', 'Batalha', 'Bombarral',
            'Caldas da Rainha', 'Castanheira de Pera', 'Figueiro dos Vinhos', 'Leiria', 'Marinha Grande', 'Nazare', 'Óbidos',
            'Pedrogão Grande', 'Peniche', 'Pombal', 'Porto de Mos', 'Alenquer', 'Arruda dos Vinhos', 'Azambuja', 'Cadaval',
            'Cascais', 'Lisboa', 'Loures', 'Lourinhã', 'Mafra', 'Oeiras', 'Sintra', 'Sobral de Monte Agraço', 'Torres Vedras',
            'Vila Franca de Xira', 'Amadora', 'Odivelas', 'Alter do Chão', 'Arronches', 'Avis', 'Campo Maior', 'Castelo de Vide',
            'Crato', 'Elvas', 'Fronteira', 'Gavião', 'Marvão', 'Monforte', 'Nisa', 'Ponte de Sor', 'Portalegre', 'Sousel',
            'Amarante', 'Baião', 'Felgueiras', 'Gondomar', 'Lousada', 'Maia', 'Marco de Canaveses', 'Matosinhos',
            'Paços de Ferreira', 'Paredes', 'Penafiel', 'Porto', 'Póvoa de Varzim', 'Santo Tirso', 'Valongo', 'Vila do Conde',
            'Vila Nova de Gaia', 'Trofa', 'Abrantes', 'Alcanena', 'Almeirim', 'Alpiarça', 'Benavente', 'Cartaxo', 'Chamusca',
            'Constancia', 'Coruche', 'Entroncamento', 'Ferreira do Zezere', 'Golegã', 'Mação', 'Rio Maior', 'Salvaterra de Magos',
            'Santarem', 'Sardoal', 'Tomar', 'Torres Novas', 'Vila Nova da Barquinha', 'Ourém', 'Alcácer do Sal', 'Alcochete',
            'Almada', 'Barreiro', 'Grandola', 'Moita', 'Montijo', 'Palmela', 'Santiago do Cacem', 'Seixal', 'Sesimbra', 'Setúbal',
            'Sines', 'Arcos de Valdevez', 'Caminha', 'Melgaço', 'Monção', 'Paredes de Coura', 'Ponte da Barca', 'Ponte de Lima',
            'Valença', 'Viana do Castelo', 'Vila Nova de Cerveira', 'Alijó', 'Boticas', 'Chaves', 'Mesão Frio', 'Mondim de Basto',
            'Montalegre', 'Murça', 'Peso da Régua', 'Ribeira de Pena', 'Sabrosa', 'Santa Marta de Penaguião', 'Valpaços',
            'Vila Pouca de Aguiar', 'Vila Real', 'Armamar', 'Carregal do Sal', 'Castro Daire', 'Cinfães', 'Lamego', 'Mangualde',
            'Moimenta da Beira', 'Mortagua', 'Nelas', 'Oliveira de Frades', 'Penalva do Castelo', 'Penedono', 'Resende',
            'Santa Comba Dão', 'S. João da Pesqueira', 'S. Pedro do Sul', 'Sátão', 'Sernancelhe', 'Tabuaço', 'Tarouca', 'Tondela',
            'Vila Nova de Paiva', 'Viseu', 'Vouzela', 'Angra do Heroismo', 'Calheta (açores)', 'Santa Cruz da Graciosa', 'Velas',
            'Vila Praia da Vitoria', 'Corvo', 'Horta', 'Lajes das Flores', 'Lajes do Pico', 'Madalena', 'Santa Cruz das Flores',
            'S. Roque do Pico', 'Lagoa (açores)', 'Nordeste', 'Ponta Delgada', 'Povoação', 'Ribeira Grande', 'Vila Franca do Campo',
            'Vila do Porto', 'Calheta (madeira)', 'Câmara de Lobos', 'Funchal', 'Machico', 'Ponta do Sol', 'Porto Moniz',
            'Porto Santo', 'Ribeira Brava', 'Santa Cruz', 'Santana', 'S. Vicente',
        ];

        DB::table('concelhos')->whereIn('nome', $nomes)->delete();
    }
};
